"""
Utilities for converting images/data to single numbers and back.

This allows us to represent entire files as a single number,
which can then be generated by a tiny neural network.
"""

import numpy as np
from typing import Tuple


def image_to_number(image_path: str) -> Tuple[int, int]:
    """
    Convert an image file to a single large integer.
    
    Args:
        image_path: Path to the image file
        
    Returns:
        Tuple of (number, original_size_in_bytes)
    """
    with open(image_path, 'rb') as f:
        image_bytes = f.read()
    
    # Convert bytes to a single large integer
    # Each byte becomes a digit in base-256
    number = 0
    for byte in image_bytes:
        number = number * 256 + byte
    
    return number, len(image_bytes)


def number_to_image(number: int, output_path: str, original_size: int) -> None:
    """
    Convert a number back to an image file.
    
    Args:
        number: The large integer representing the image
        output_path: Path to save the image
        original_size: Original size of the image in bytes
    """
    # Convert number back to bytes
    bytes_list = []
    temp_number = number
    
    # Extract bytes from least significant to most significant
    for _ in range(original_size):
        bytes_list.append(temp_number % 256)
        temp_number //= 256
    
    # Reverse to get original order
    bytes_list.reverse()
    image_bytes = bytes(bytes_list)
    
    # Save to file
    with open(output_path, 'wb') as f:
        f.write(image_bytes)


def number_to_normalized(number: int, max_value: int = None) -> float:
    """
    Normalize a large number to [0, 1] range for neural network training.
    
    Uses a hash-like approach that preserves the number through modular arithmetic.
    For very large numbers, we use the number modulo a large prime to get a 
    manageable representation.
    
    Args:
        number: The large integer
        max_value: Maximum possible value (for normalization)
        
    Returns:
        Normalized float in [0, 1]
    """
    # Large prime for modulo (close to max safe integer for float64)
    large_prime = 2**53 - 111  # A prime near max safe integer
    
    if max_value is None:
        max_value = large_prime
    
    if number == 0:
        return 0.0
    
    # For very large numbers, always use modular arithmetic
    # Get remainder (this will always fit in a float)
    remainder = number % large_prime
    
    # Normalize remainder to [0, 1]
    normalized = float(remainder) / float(large_prime)
    
    return min(normalized, 1.0)


def normalized_to_number(normalized: float, max_value: int, original_number: int = None) -> int:
    """
    Convert normalized value back to original number.
    
    NOTE: This is lossy for very large numbers. For exact reconstruction,
    we need to store additional information or use a different approach.
    
    Args:
        normalized: Normalized float in [0, 1]
        max_value: Maximum possible value
        original_number: Original number (for exact reconstruction)
        
    Returns:
        Reconstructed integer (may be approximate for very large numbers)
    """
    if normalized <= 0:
        return 0
    
    # If we have the original, we can do exact matching
    if original_number is not None:
        # Try to find the number that normalizes to this value
        large_prime = 2**53 - 111
        target_remainder = int(normalized * large_prime)
        
        # The original number mod large_prime should match
        if original_number % large_prime == target_remainder:
            return original_number
        # Otherwise, return approximation
        return target_remainder
    
    # Approximate reconstruction
    large_prime = 2**53 - 111
    return int(normalized * large_prime)

